# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4af92ed0169c7989ca07abb2b7687695"
name = "Bundle_Final"
handle = "bundle_final"
application_url = "https://mess-cooler-je-weapon.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "new-store-test-bun.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_orders,read_publications,read_themes,write_cart_transforms,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://mess-cooler-je-weapon.trycloudflare.com/auth/callback",
  "https://mess-cooler-je-weapon.trycloudflare.com/auth/shopify/callback",
  "https://mess-cooler-je-weapon.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "orders/create", "products/update" ]
  uri = "/webhooks"

[pos]
embedded = false
